[package]
name = "water"
version = "0.1.0"
edition = "2021"

[features]
gpio = []
term_logger = []

[dependencies]
time = { version = "0.3.5", features = ["local-offset", "formatting"] }
gpio-cdev = "0.5.1"
log = "0.4.14"
simplelog = "0.11.2"
